### PR TITLE
fixes to compile with esp-idf 5.2

### LINKED ISSUE #1: Library does not seem to build correctly with idf.py v5.2
Unless I've made an installation error, it looks like the component.mk file is either not used or not correctly specified.

Steps:
* copy examples/hello_word from esp-idf examples...
* put pcf8757_pro directory in hello_world/components directory
* idf.py set-target esp32
* idf.py create-manifest --component=pcf8757_pro
* idf.py reconfigure
* add #include "PCF.h" at top of hello_world
* idf.py build

the build fails with:
```
FAILED: esp-idf/pcf8575_pro/CMakeFiles/__idf_pcf8575_pro.dir/PCF.c.obj
bin/xtensa-esp32-elf-gcc -DESP_PLATFORM -DIDF_VER=\"v5.2-dev-2158-gdb4308888d\" -DSOC_MMU_PAGE_SIZE=CONFIG_MMU_PAGE_SIZE -DSOC_XTAL_FREQ_MHZ=CONFIG_XTAL_FREQ -D_GLIBCXX_HAVE_POSIX_SEMAPHORE -D_GLIBCXX_USE_POSIX_SEMAPHORE -D_GNU_SOURCE -D_POSIX_READER_WRITER_LOCKS -I/Users/.../src/esp/hello_world/build/config -I/Users/.../src/esp/hello_world/components/pcf8575_pro -I/Users/.../src/esp/esp-idf/components/newlib/platform_include -I/Users/.../src/esp/esp-idf/components/freertos/config/include -I/Users/.../src/esp/esp-idf/components/freertos/config/include/freertos -I/Users/
...
hello_world/components/pcf8575_pro/PCF.h:5:10: fatal error: i2cdev.h: No such file or directory
    5 | #include <i2cdev.h>
```

Looks like idf.py is not providing the right include dirs when building PCF.c as a component of hello_world and/or the PCF code should be referring to the <i2cdev/i2cdev.h> instead...

### PR DESCRIPTION
**Pull request by aathan**
Attempts to fix #1. This pull request is not quite ready. Looks like I need to figure out how to incorporate the sub-directories into the cmake system, because idf.py menuconfig on the main project does not bring up the Kconfigs of those subdirs. Alternatively, these can be pulled up into the top level Kconfig etc. I'm not familiar with how to use the idf build system in advanced ways yet, but this fix is close.

### CODE REVIEW

**Comment by xuanphu1** [comment]
you can try run my code after I was update :D
